version: '0'

services:

  web:
    build: ./
    ports:
      - 8080:8080
#    volumes:
#      - web
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306  # cannot change this port to other number
      MYSQL_DATABASE: 'mhealth_database'
      MYSQL_ROOT_PASSWORD: 'administrator'

    ports:
      - 3306:3306

    volumes:
      - mysql:/data

    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5


#Names our volume
volumes:
  mysql: