version: '0'

services:

  web:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - "db"
    restart: always

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306  # cannot change this port to other number
      MYSQL_DATABASE: 'mhealth_database'
      MYSQL_ROOT_PASSWORD: 'administrator'

    ports:
      - 3306:3306

#    expose:
#      # Opens port 8080 on the container
#      - "8080"
#      # where our data will be persisted

    volumes:
      - mysql:/data

#Names our volume
volumes:
  mysql: