version: '0'

services:

  web:
    build: ./
    ports:
      - 80:8080
    volumes:
      - ./:/app

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mhealth_database'
      MYSQL_PASSWORD: 'administrator'
      # password for root access
      MYSQL_ROOT_PASSWORD: 'administrator'
    ports:
      - 3306:3306

#    expose:
#      # Opens port 8080 on the container
#      - "8080"
#      # where our data will be persisted

    volumes:
      - mysql:/data

#Names our volume
volumes:
  mysql: