# Generated by Django 4.0.8 on 2022-12-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
