# Generated by Django 4.0.8 on 2023-01-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('first_name', models.CharField(default='x', max_length=32)),
                ('last_name', models.CharField(default='x', max_length=32)),
                ('gender', models.CharField(default='x', max_length=32)),
                ('race', models.CharField(default='x', max_length=32)),
                ('dob', models.CharField(default='x', max_length=32)),
                ('first_language', models.CharField(default='x', max_length=32)),
                ('smoke', models.CharField(default='no', max_length=3)),
            ],
        ),
    ]
